import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/665",
  size: 18,
  colorRegions: [
    ["O", "C", "C", "C", "C", "E", "C", "R", "R", "R", "C", "E", "C", "C", "C", "C", "O", "C"],
    ["C", "E", "C", "C", "O", "C", "E", "D", "D", "D", "E", "C", "O", "C", "C", "E", "C", "E"],
    ["C", "C", "E", "E", "C", "C", "C", "D", "D", "D", "C", "C", "C", "E", "E", "C", "C", "C"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "D", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "B", "C", "C", "C", "G", "C", "C", "C", "B", "C", "C", "C", "G", "C", "C", "C"],
    ["C", "B", "B", "C", "C", "B", "B", "B", "C", "B", "B", "B", "C", "B", "B", "C", "C", "C"],
    ["C", "B", "G", "B", "C", "B", "I", "B", "C", "B", "G", "B", "C", "B", "I", "B", "C", "C"],
    ["C", "C", "F", "C", "C", "C", "F", "C", "C", "C", "F", "C", "C", "C", "A", "C", "C", "C"],
    ["C", "C", "F", "C", "J", "C", "A", "C", "J", "C", "A", "C", "J", "C", "A", "C", "C", "C"],
    ["C", "C", "F", "J", "J", "C", "F", "J", "J", "J", "F", "C", "J", "J", "A", "C", "C", "C"],
    ["C", "C", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "C", "C", "C"],
    ["C", "L", "L", "L", "L", "L", "L", "P", "L", "L", "L", "L", "L", "L", "L", "L", "C", "C"],
    ["C", "L", "L", "L", "L", "L", "L", "P", "L", "P", "L", "L", "L", "L", "L", "L", "C", "K"],
    ["N", "L", "H", "L", "H", "L", "H", "P", "P", "P", "H", "L", "H", "L", "H", "L", "C", "K"],
    ["M", "L", "Q", "Q", "Q", "L", "Q", "Q", "Q", "P", "Q", "Q", "Q", "L", "Q", "L", "K", "K"],
    ["M", "H", "H", "H", "H", "H", "H", "H", "H", "P", "H", "H", "H", "H", "H", "H", "K", "N"],
    ["N", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "N", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;