import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/634",
  size: 18,
  colorRegions: [
    ["C", "N", "N", "N", "C", "C", "C", "C", "G", "G", "C", "C", "C", "C", "N", "I", "N", "C"],
    ["C", "I", "E", "N", "C", "C", "F", "F", "F", "F", "F", "F", "C", "C", "I", "E", "I", "C"],
    ["C", "I", "I", "N", "C", "C", "R", "R", "R", "R", "R", "R", "C", "C", "I", "N", "I", "C"],
    ["C", "C", "E", "C", "C", "R", "B", "A", "D", "J", "L", "D", "R", "C", "C", "E", "C", "C"],
    ["C", "C", "E", "C", "R", "D", "L", "D", "L", "B", "D", "B", "D", "R", "C", "E", "C", "C"],
    ["C", "C", "E", "C", "R", "J", "A", "J", "B", "A", "B", "J", "B", "R", "C", "E", "C", "C"],
    ["C", "C", "C", "C", "R", "D", "B", "L", "J", "L", "D", "B", "D", "R", "C", "C", "C", "C"],
    ["C", "C", "C", "C", "C", "R", "D", "B", "A", "J", "L", "A", "R", "C", "C", "C", "C", "C"],
    ["M", "Q", "K", "K", "C", "C", "R", "R", "R", "R", "R", "R", "C", "C", "Q", "K", "K", "C"],
    ["M", "Q", "E", "K", "M", "C", "F", "F", "F", "F", "F", "F", "C", "M", "K", "E", "Q", "M"],
    ["M", "Q", "Q", "K", "M", "C", "F", "F", "F", "F", "F", "F", "C", "M", "Q", "Q", "Q", "M"],
    ["M", "M", "O", "M", "C", "C", "F", "F", "F", "F", "F", "F", "C", "M", "M", "O", "M", "M"],
    ["P", "M", "O", "P", "P", "F", "F", "F", "F", "E", "F", "F", "F", "M", "M", "O", "M", "M"],
    ["P", "P", "O", "P", "P", "F", "F", "F", "E", "F", "F", "F", "F", "P", "M", "O", "M", "P"],
    ["P", "P", "O", "P", "P", "F", "F", "F", "F", "F", "F", "F", "F", "P", "P", "O", "P", "P"],
    ["P", "O", "O", "O", "F", "F", "F", "F", "H", "H", "F", "F", "F", "F", "O", "O", "O", "P"],
    ["P", "P", "P", "P", "H", "F", "F", "F", "H", "H", "F", "F", "F", "H", "P", "P", "P", "P"],
    ["P", "P", "P", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "P", "P", "P", "P"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;