import {
  altoMain,
  anakiwa,
  atomicTangerine,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/528",
  size: 16,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "D", "D", "D", "D"],
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "C", "D", "D"],
    ["E", "A", "A", "A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "D", "D", "D"],
    ["F", "F", "F", "A", "A", "G", "G", "B", "B", "G", "G", "C", "D", "D", "D", "D"],
    ["H", "F", "F", "F", "G", "G", "G", "B", "B", "G", "G", "G", "D", "D", "D", "D"],
    ["H", "F", "F", "F", "G", "G", "G", "G", "B", "G", "G", "G", "D", "D", "D", "D"],
    ["H", "H", "F", "F", "F", "F", "F", "G", "G", "G", "I", "I", "I", "I", "D", "D"],
    ["H", "H", "F", "F", "F", "F", "G", "G", "G", "I", "I", "I", "I", "I", "D", "J"],
    ["H", "H", "F", "F", "G", "G", "G", "G", "G", "G", "G", "G", "I", "I", "D", "J"],
    ["H", "H", "F", "F", "G", "G", "G", "K", "G", "G", "G", "G", "L", "I", "I", "J"],
    ["H", "H", "F", "F", "K", "G", "G", "K", "M", "G", "G", "N", "L", "L", "I", "J"],
    ["F", "F", "F", "F", "K", "K", "K", "K", "O", "O", "N", "N", "L", "L", "L", "L"],
    ["F", "F", "F", "F", "F", "K", "K", "K", "O", "O", "O", "O", "O", "L", "O", "L"],
    ["F", "F", "F", "F", "F", "F", "F", "K", "O", "O", "O", "O", "O", "O", "O", "O"],
    ["F", "F", "F", "F", "F", "F", "F", "K", "O", "O", "P", "O", "O", "O", "O", "O"],
    ["F", "F", "F", "F", "F", "F", "F", "O", "O", "O", "P", "P", "O", "O", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: macNCheese,
    G: lightGreen,
    H: white,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: saharaSand,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
