import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/544",
  size: 16,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["D", "D", "A", "A", "A", "B", "B", "C", "E", "C", "E", "C", "C", "C", "C", "C"],
    ["D", "F", "F", "A", "A", "B", "E", "E", "E", "E", "E", "C", "C", "C", "C", "C"],
    ["D", "D", "D", "D", "D", "B", "E", "E", "E", "E", "E", "E", "E", "G", "C", "C"],
    ["D", "D", "D", "D", "D", "B", "B", "B", "B", "B", "B", "E", "E", "G", "C", "C"],
    ["D", "D", "D", "D", "D", "B", "B", "H", "H", "H", "H", "H", "E", "E", "C", "C"],
    ["D", "D", "D", "D", "D", "B", "B", "B", "B", "H", "I", "I", "E", "E", "C", "C"],
    ["D", "D", "D", "J", "J", "J", "J", "B", "B", "B", "I", "I", "I", "I", "I", "I"],
    ["D", "D", "D", "K", "J", "J", "J", "J", "B", "B", "B", "B", "I", "I", "I", "I"],
    ["D", "D", "D", "K", "J", "J", "J", "J", "L", "L", "L", "B", "B", "I", "I", "M"],
    ["D", "D", "D", "K", "J", "J", "J", "J", "J", "L", "L", "B", "B", "I", "I", "M"],
    ["D", "D", "D", "K", "J", "J", "J", "J", "J", "L", "L", "L", "N", "O", "O", "M"],
    ["D", "D", "D", "K", "K", "K", "J", "J", "J", "P", "P", "N", "N", "N", "O", "O"],
    ["D", "D", "D", "K", "K", "K", "K", "J", "J", "P", "P", "N", "N", "N", "N", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
