import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/636",
  size: 14,
  colorRegions: [
    ["B", "B", "C", "C", "C", "M", "M", "M", "M", "M", "M", "M", "M", "M"],
    ["B", "C", "C", "C", "C", "M", "M", "M", "M", "M", "M", "M", "N", "M"],
    ["B", "C", "C", "C", "C", "L", "M", "M", "M", "M", "M", "M", "N", "M"],
    ["B", "B", "C", "C", "C", "L", "K", "K", "M", "M", "M", "M", "N", "M"],
    ["E", "B", "C", "C", "C", "L", "L", "K", "K", "A", "M", "M", "N", "M"],
    ["E", "E", "E", "C", "C", "C", "C", "C", "K", "A", "M", "M", "N", "N"],
    ["E", "E", "E", "E", "D", "D", "K", "K", "K", "A", "M", "N", "N", "N"],
    ["D", "D", "D", "D", "D", "K", "K", "K", "K", "A", "A", "A", "A", "A"],
    ["D", "D", "D", "D", "D", "K", "K", "K", "K", "K", "K", "K", "A", "A"],
    ["D", "F", "F", "K", "K", "K", "K", "K", "K", "K", "K", "H", "I", "A"],
    ["F", "F", "K", "K", "K", "K", "K", "K", "K", "H", "H", "H", "I", "A"],
    ["F", "G", "K", "K", "K", "H", "H", "K", "K", "H", "I", "I", "I", "A"],
    ["F", "G", "G", "G", "K", "H", "H", "H", "H", "H", "I", "H", "J", "A"],
    ["F", "F", "G", "G", "K", "H", "H", "H", "H", "H", "H", "H", "J", "A"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;
