import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/664",
  size: 17,
  colorRegions: [
    ["A", "A", "A", "A", "A", "E", "E", "E", "E", "E", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "D", "D", "D", "D", "D", "Q", "F", "Q", "E", "E", "E", "C", "C", "B", "B"],
    ["A", "D", "D", "K", "K", "K", "F", "E", "E", "E", "F", "E", "E", "O", "C", "C", "B"],
    ["A", "K", "K", "K", "K", "Q", "E", "E", "E", "E", "E", "Q", "E", "O", "O", "O", "B"],
    ["A", "L", "L", "E", "F", "E", "E", "E", "N", "E", "E", "E", "F", "E", "O", "O", "B"],
    ["A", "L", "L", "E", "Q", "E", "E", "M", "N", "E", "E", "E", "Q", "E", "O", "O", "B"],
    ["A", "L", "L", "E", "F", "E", "E", "M", "N", "E", "E", "E", "F", "E", "O", "O", "B"],
    ["L", "L", "L", "E", "E", "E", "E", "E", "N", "E", "E", "E", "Q", "E", "O", "O", "O"],
    ["L", "L", "L", "L", "E", "E", "E", "E", "E", "E", "E", "E", "F", "E", "E", "O", "O"],
    ["L", "L", "L", "L", "E", "E", "E", "E", "E", "E", "E", "E", "Q", "E", "E", "E", "O"],
    ["L", "L", "L", "L", "E", "E", "E", "E", "E", "E", "E", "E", "F", "E", "E", "E", "O"],
    ["G", "L", "L", "L", "E", "E", "E", "E", "E", "E", "E", "E", "Q", "E", "E", "E", "H"],
    ["G", "L", "L", "L", "L", "E", "E", "E", "E", "E", "P", "E", "F", "E", "E", "E", "H"],
    ["G", "L", "L", "L", "L", "L", "E", "E", "E", "E", "P", "P", "Q", "E", "E", "E", "H"],
    ["G", "J", "L", "L", "L", "L", "E", "E", "E", "E", "E", "P", "F", "E", "I", "I", "H"],
    ["G", "J", "J", "J", "L", "L", "E", "E", "E", "E", "P", "P", "Q", "I", "I", "H", "H"],
    ["G", "G", "G", "L", "L", "L", "P", "P", "P", "P", "P", "P", "F", "H", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;