import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lavenderRose,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/647",
  size: 18,
  colorRegions: [
    ["D", "D", "D", "K", "K", "K", "K", "K", "K", "K", "B", "B", "B", "B", "B", "P", "P", "P"],
    ["D", "E", "E", "E", "I", "I", "K", "K", "K", "K", "B", "K", "K", "K", "B", "N", "N", "P"],
    ["D", "E", "L", "L", "I", "L", "I", "K", "K", "K", "B", "K", "K", "K", "B", "R", "N", "P"],
    ["D", "E", "L", "L", "I", "L", "I", "H", "H", "B", "B", "R", "K", "B", "B", "R", "N", "K"],
    ["D", "E", "L", "L", "I", "L", "I", "H", "H", "B", "B", "R", "R", "B", "B", "R", "R", "K"],
    ["K", "E", "L", "L", "I", "I", "H", "H", "H", "H", "H", "R", "R", "R", "R", "R", "R", "K"],
    ["K", "E", "L", "I", "I", "H", "H", "H", "H", "C", "C", "R", "R", "R", "R", "R", "A", "K"],
    ["K", "I", "I", "J", "I", "H", "H", "H", "C", "H", "H", "C", "H", "C", "R", "R", "A", "K"],
    ["K", "I", "J", "J", "I", "H", "H", "H", "H", "H", "H", "C", "H", "R", "R", "R", "K", "K"],
    ["K", "I", "J", "J", "I", "I", "I", "H", "H", "H", "H", "C", "H", "H", "R", "R", "K", "K"],
    ["K", "I", "J", "I", "I", "J", "J", "I", "H", "H", "H", "C", "H", "C", "R", "R", "K", "K"],
    ["K", "I", "J", "J", "I", "J", "J", "I", "H", "H", "C", "H", "H", "H", "R", "R", "F", "K"],
    ["K", "O", "I", "J", "I", "J", "I", "H", "H", "C", "H", "H", "H", "H", "R", "R", "F", "K"],
    ["K", "O", "J", "I", "I", "I", "R", "R", "G", "R", "G", "R", "R", "R", "R", "R", "F", "K"],
    ["K", "O", "J", "J", "I", "R", "R", "G", "G", "G", "G", "G", "R", "R", "F", "F", "F", "K"],
    ["Q", "I", "J", "J", "I", "R", "R", "R", "G", "R", "G", "R", "R", "R", "F", "R", "F", "K"],
    ["Q", "O", "I", "I", "I", "O", "O", "G", "G", "G", "G", "G", "A", "A", "F", "F", "F", "M"],
    ["Q", "Q", "Q", "Q", "Q", "K", "K", "K", "G", "M", "G", "A", "A", "M", "M", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: lavenderRose,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;