import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/629",
  size: 18,
  colorRegions: [
    ["G", "G", "G", "Q", "Q", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["G", "G", "G", "L", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "E", "E", "E", "C"],
    ["G", "G", "G", "Q", "Q", "C", "C", "B", "B", "B", "B", "C", "C", "E", "E", "E", "E", "E"],
    ["Q", "L", "Q", "L", "C", "C", "B", "C", "C", "C", "C", "B", "C", "C", "E", "E", "E", "C"],
    ["Q", "C", "Q", "C", "C", "C", "C", "B", "H", "H", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "C", "R", "C", "J", "J", "J", "H", "H", "C", "C", "C", "C", "A", "C", "C", "C"],
    ["J", "J", "R", "I", "R", "J", "H", "H", "H", "H", "H", "H", "J", "A", "I", "A", "J", "J"],
    ["J", "J", "J", "R", "J", "J", "H", "H", "H", "H", "H", "H", "J", "J", "A", "J", "J", "J"],
    ["J", "J", "J", "J", "J", "J", "J", "J", "H", "H", "J", "J", "J", "J", "J", "J", "J", "J"],
    ["J", "P", "I", "O", "K", "K", "K", "J", "H", "H", "J", "K", "K", "K", "O", "P", "I", "J"],
    ["J", "O", "B", "P", "K", "K", "J", "J", "H", "H", "J", "J", "K", "K", "I", "B", "O", "J"],
    ["J", "I", "P", "I", "K", "K", "J", "N", "N", "N", "N", "J", "J", "K", "P", "O", "P", "J"],
    ["J", "K", "F", "K", "K", "J", "J", "N", "D", "D", "N", "N", "J", "K", "K", "F", "K", "J"],
    ["K", "F", "F", "K", "K", "J", "N", "N", "D", "D", "D", "N", "N", "K", "K", "F", "F", "K"],
    ["K", "K", "F", "K", "K", "K", "N", "D", "D", "M", "D", "D", "N", "N", "K", "F", "K", "K"],
    ["K", "N", "N", "N", "N", "N", "N", "D", "M", "M", "M", "D", "N", "N", "N", "N", "N", "K"],
    ["N", "N", "N", "N", "N", "N", "D", "D", "D", "M", "D", "D", "D", "D", "D", "N", "N", "N"],
    ["N", "N", "D", "D", "D", "D", "D", "D", "D", "M", "D", "D", "D", "D", "D", "D", "N", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;