import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/663",
  size: 18,
  colorRegions: [
    ["C", "C", "C", "F", "F", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "F", "F", "F", "F", "F", "C", "C", "A", "C", "C", "C", "C", "C", "C", "L", "C"],
    ["C", "F", "F", "F", "F", "F", "F", "F", "C", "C", "A", "C", "C", "I", "C", "C", "C", "L"],
    ["C", "O", "O", "O", "O", "O", "O", "O", "C", "B", "C", "C", "I", "C", "C", "C", "L", "C"],
    ["C", "O", "G", "O", "G", "O", "G", "O", "C", "C", "B", "C", "C", "I", "C", "C", "C", "C"],
    ["C", "O", "O", "O", "O", "O", "O", "O", "C", "B", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "F", "F", "F", "F", "F", "F", "F", "C", "C", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "F", "J", "F", "J", "F", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "P", "R", "J", "R", "J", "R", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "P", "R", "R", "R", "R", "R", "J", "J", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["P", "P", "F", "F", "F", "F", "F", "D", "D", "J", "J", "C", "C", "C", "C", "C", "C", "C"],
    ["P", "N", "F", "F", "F", "F", "F", "K", "D", "D", "D", "J", "C", "C", "C", "C", "C", "C"],
    ["P", "N", "R", "R", "E", "R", "R", "K", "K", "M", "M", "D", "J", "J", "J", "J", "C", "C"],
    ["N", "N", "R", "E", "E", "E", "R", "K", "K", "K", "M", "M", "M", "M", "M", "J", "J", "J"],
    ["K", "K", "F", "E", "E", "E", "F", "K", "K", "K", "K", "Q", "Q", "Q", "M", "D", "D", "D"],
    ["K", "K", "F", "E", "E", "E", "F", "K", "K", "K", "K", "K", "Q", "Q", "Q", "Q", "Q", "D"],
    ["K", "K", "H", "E", "E", "E", "H", "K", "K", "K", "K", "K", "K", "Q", "Q", "Q", "Q", "Q"],
    ["K", "H", "H", "H", "H", "H", "H", "H", "K", "K", "K", "K", "K", "K", "Q", "Q", "Q", "Q"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: halfBaked,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;