import {
  lightWisteria,
  chardonnay,
  anakiwa,
  celadon,
  altoMain,
  bittersweet,
  saharaSand,
  nomad,
  lightOrchid,
  halfBaked,
  turquoiseBlue,
  atomicTangerine,
  lightGreen,
  emerald,
  periwinkle,
  lavenderRose,
  macNCheese,
  white,
} from "../colors";

const level = {
  path: "/community-level/653",
  size: 18,
  colorRegions: [
    ["B", "B", "B", "B", "I", "I", "C", "C", "C", "C", "C", "R", "R", "R", "C", "C", "C", "C"],
    ["B", "B", "B", "Q", "C", "C", "C", "C", "C", "G", "O", "G", "O", "G", "O", "G", "G", "C"],
    ["B", "B", "I", "C", "C", "C", "C", "O", "O", "G", "O", "G", "O", "G", "O", "G", "K", "C"],
    ["B", "Q", "C", "I", "C", "C", "C", "C", "O", "G", "O", "G", "O", "G", "O", "G", "G", "C"],
    ["I", "C", "C", "C", "C", "C", "C", "C", "C", "G", "O", "G", "O", "G", "O", "C", "C", "C"],
    ["I", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "C", "P", "C", "J", "C", "C", "C", "C", "J", "C"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "G", "C", "C", "C", "C", "L", "G", "P"],
    ["C", "C", "C", "C", "D", "D", "C", "C", "C", "L", "M", "P", "C", "C", "C", "C", "J", "C"],
    ["C", "C", "C", "D", "D", "D", "E", "D", "D", "D", "M", "D", "D", "D", "D", "D", "M", "D"],
    ["C", "C", "D", "D", "D", "D", "D", "E", "D", "D", "M", "D", "D", "D", "D", "D", "M", "D"],
    ["C", "K", "K", "K", "D", "D", "E", "D", "E", "D", "M", "D", "D", "D", "D", "D", "M", "D"],
    ["K", "D", "D", "D", "K", "E", "D", "D", "D", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    ["E", "E", "E", "E", "E", "N", "N", "D", "D", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    ["E", "E", "E", "E", "E", "N", "N", "D", "D", "D", "F", "A", "A", "A", "F", "F", "F", "N"],
    ["E", "E", "E", "E", "E", "N", "N", "N", "D", "D", "F", "F", "F", "A", "A", "A", "F", "N"],
    ["E", "E", "E", "E", "E", "N", "N", "N", "N", "N", "N", "H", "H", "H", "H", "H", "N", "N"],
    ["E", "E", "E", "E", "E", "N", "N", "N", "N", "N", "N", "N", "H", "H", "H", "N", "N", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: lavenderRose,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;