import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/515",
  size: 16,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B"],
    ["A", "A", "A", "A", "C", "A", "A", "A", "A", "D", "D", "A", "A", "B", "D", "D"],
    ["A", "A", "A", "A", "C", "A", "A", "A", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "E", "E", "F", "F", "A", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "E", "E", "E", "E", "A", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "E", "E", "E", "E", "A", "A", "D", "D", "D", "D", "D", "G", "G"],
    ["A", "A", "A", "E", "E", "E", "E", "A", "A", "D", "D", "H", "H", "H", "G", "G"],
    ["A", "A", "A", "E", "E", "E", "E", "E", "A", "D", "D", "I", "I", "H", "H", "H"],
    ["A", "A", "A", "A", "E", "A", "E", "J", "J", "D", "D", "I", "I", "H", "H", "H"],
    ["A", "A", "A", "A", "A", "A", "E", "J", "K", "K", "K", "K", "I", "H", "H", "H"],
    ["L", "A", "A", "A", "A", "A", "E", "E", "E", "E", "M", "M", "M", "H", "H", "H"],
    ["L", "A", "A", "A", "A", "N", "N", "E", "E", "E", "M", "M", "M", "H", "H", "H"],
    ["L", "O", "A", "A", "A", "N", "N", "E", "E", "E", "M", "M", "M", "P", "P", "H"],
    ["L", "O", "A", "A", "A", "N", "N", "E", "E", "E", "E", "E", "M", "M", "M", "M"],
    ["L", "L", "A", "A", "A", "A", "N", "E", "E", "E", "E", "M", "M", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
