import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/645",
  size: 15,
  colorRegions: [
    ["M", "O", "O", "O", "O", "M", "M", "M", "N", "M", "N", "M", "N", "N", "M"],
    ["O", "O", "O", "M", "A", "M", "K", "K", "K", "M", "K", "M", "N", "N", "M"],
    ["O", "O", "M", "M", "L", "B", "M", "K", "K", "K", "K", "K", "C", "N", "N"],
    ["O", "M", "L", "L", "L", "L", "K", "K", "K", "K", "K", "K", "K", "K", "N"],
    ["O", "L", "L", "L", "L", "L", "E", "K", "K", "K", "K", "K", "K", "K", "F"],
    ["O", "O", "O", "L", "L", "L", "L", "K", "M", "M", "K", "M", "K", "G", "N"],
    ["O", "O", "O", "O", "L", "L", "D", "K", "K", "M", "M", "M", "K", "N", "N"],
    ["O", "M", "M", "M", "L", "L", "L", "C", "M", "M", "J", "M", "N", "N", "M"],
    ["O", "M", "M", "M", "H", "I", "L", "M", "M", "M", "J", "M", "N", "N", "M"],
    ["O", "M", "M", "G", "I", "I", "L", "M", "M", "M", "J", "M", "N", "N", "M"],
    ["M", "M", "F", "I", "I", "I", "M", "J", "J", "J", "J", "E", "N", "N", "N"],
    ["M", "M", "M", "I", "I", "I", "I", "J", "M", "M", "J", "J", "D", "N", "M"],
    ["M", "I", "I", "I", "I", "I", "M", "M", "J", "J", "J", "J", "J", "N", "N"],
    ["M", "M", "M", "M", "I", "I", "M", "B", "J", "J", "J", "M", "N", "N", "M"],
    ["M", "M", "M", "M", "I", "M", "M", "M", "A", "J", "J", "J", "J", "H", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "Ja-Nice",
  creatorLink: "https://www.linkedin.com/in/jan-hollmann-215a85315",
};

export default level;
