import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/549",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "D", "D"],
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "D"],
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "D"],
    ["A", "A", "A", "A", "B", "B", "E", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "B", "E", "E", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "F", "A", "A", "B", "E", "E", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "G", "G", "G", "G", "G", "G", "B", "B", "B", "B"],
    ["A", "A", "A", "H", "H", "H", "H", "H", "H", "H", "G", "B", "B", "B", "B"],
    ["A", "A", "A", "H", "H", "H", "I", "I", "H", "J", "G", "B", "B", "B", "B"],
    ["A", "A", "A", "H", "H", "H", "H", "I", "J", "J", "G", "G", "G", "B", "B"],
    ["A", "A", "H", "H", "H", "H", "H", "H", "K", "K", "K", "K", "G", "B", "B"],
    ["A", "A", "L", "H", "H", "H", "H", "H", "K", "K", "K", "M", "G", "G", "B"],
    ["A", "L", "L", "H", "H", "H", "H", "H", "K", "K", "K", "M", "N", "G", "B"],
    ["A", "A", "L", "L", "H", "H", "H", "H", "K", "K", "K", "K", "N", "O", "O"],
    ["A", "A", "L", "L", "H", "H", "H", "K", "K", "K", "K", "K", "N", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
