import {
  anakiwa,
  atomicTangerine,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/599",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "D", "D", "D", "A", "A", "B", "B", "B", "C", "C", "E", "E"],
    ["A", "D", "A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "E"],
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "E"],
    ["A", "A", "A", "A", "F", "F", "B", "F", "F", "C", "C", "C", "E"],
    ["A", "A", "A", "A", "A", "F", "F", "F", "C", "C", "C", "G", "G"],
    ["A", "A", "A", "A", "A", "F", "F", "F", "C", "C", "G", "G", "G"],
    ["A", "A", "A", "A", "F", "F", "H", "F", "F", "H", "H", "G", "G"],
    ["I", "I", "I", "I", "I", "I", "H", "H", "H", "H", "H", "G", "G"],
    ["J", "K", "I", "I", "I", "I", "H", "H", "H", "H", "G", "G", "G"],
    ["J", "K", "I", "I", "I", "I", "H", "H", "H", "H", "G", "G", "L"],
    ["J", "K", "K", "M", "I", "M", "H", "H", "H", "H", "L", "L", "L"],
    ["M", "M", "M", "M", "M", "M", "M", "H", "H", "H", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: macNCheese,
    F: white,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
