import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  halfBaked,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/777",
  size: 13,
  colorRegions: [
    ["G", "G", "G", "G", "G", "B", "A", "A", "G", "A", "G", "A", "A"],
    ["H", "F", "F", "F", "G", "D", "D", "D", "D", "D", "D", "E", "A"],
    ["H", "G", "G", "F", "G", "L", "G", "L", "G", "L", "E", "D", "A"],
    ["H", "G", "F", "G", "G", "G", "G", "G", "G", "E", "L", "D", "G"],
    ["H", "F", "G", "G", "G", "F", "F", "F", "G", "C", "G", "D", "A"],
    ["J", "I", "M", "H", "G", "G", "G", "F", "G", "C", "L", "D", "B"],
    ["M", "G", "M", "H", "G", "G", "F", "G", "G", "G", "G", "G", "G"],
    ["M", "I", "M", "H", "G", "F", "G", "G", "G", "F", "F", "F", "G"],
    ["M", "G", "M", "H", "E", "G", "G", "G", "G", "G", "G", "F", "G"],
    ["M", "I", "M", "H", "H", "H", "I", "H", "G", "G", "F", "G", "G"],
    ["M", "G", "H", "M", "M", "M", "M", "M", "G", "F", "G", "G", "G"],
    ["K", "H", "G", "G", "I", "G", "I", "G", "G", "G", "G", "G", "G"],
    ["H", "K", "M", "M", "M", "J", "M", "M", "H", "H", "H", "H", "G"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: white,
    I: nomad,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
