import {
  altoMain,
  anakiwa,
  chardonnay,
  emerald,
  halfBaked,
  lavenderRose,
  lightOrchid,
  lightWisteria,
  macNCheese,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/710",
  size: 13,
  colorRegions: [
    ["D", "B", "F", "F", "B", "D", "C", "C", "C", "C", "M", "M", "M"],
    ["D", "F", "F", "F", "F", "D", "C", "C", "C", "C", "C", "C", "M"],
    ["D", "F", "F", "F", "F", "D", "D", "C", "C", "C", "C", "C", "C"],
    ["D", "B", "F", "F", "B", "D", "G", "D", "C", "C", "C", "C", "C"],
    ["I", "I", "D", "D", "D", "D", "G", "G", "I", "I", "C", "E", "E"],
    ["I", "I", "I", "C", "C", "C", "G", "G", "G", "I", "I", "L", "L"],
    ["L", "I", "I", "I", "I", "C", "G", "G", "G", "G", "I", "I", "L"],
    ["L", "L", "I", "I", "I", "I", "G", "H", "G", "G", "G", "I", "L"],
    ["L", "L", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    ["L", "L", "L", "H", "H", "H", "H", "H", "H", "H", "H", "H", "L"],
    ["K", "K", "L", "K", "H", "H", "H", "H", "H", "H", "H", "K", "K"],
    ["A", "A", "K", "K", "K", "K", "K", "K", "K", "K", "K", "K", "A"],
    ["J", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
  ],
  regionColors: {
    A: turquoiseBlue,
    B: chardonnay,
    C: anakiwa,
    D: lightOrchid,
    E: altoMain,
    F: saharaSand,
    G: white,
    H: macNCheese,
    I: lavenderRose,
    J: lightWisteria,
    K: halfBaked,
    L: emerald,
    M: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
