import {
  anakiwa,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lavenderRose,
  lightOrchid,
  lightWisteria,
  periwinkle,
  turquoiseBlue,
  altoMain,
  saharaSand,
  atomicTangerine,
  nomad,
  lightGreen,
  white,
} from "../colors";

const level = {
  path: "/community-level/715",
  size: 17,
  colorRegions: [
    ["G", "A", "A", "A", "A", "A", "H", "H", "H", "H", "L", "H", "H", "H", "H", "L", "L"],
    ["G", "A", "A", "A", "H", "A", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "L"],
    ["G", "G", "A", "O", "A", "A", "H", "H", "H", "H", "H", "L", "L", "O", "L", "L", "L"],
    ["G", "A", "O", "J", "O", "B", "B", "O", "I", "O", "B", "B", "O", "B", "O", "L", "L"],
    ["G", "A", "O", "P", "B", "O", "O", "B", "I", "B", "O", "O", "B", "P", "O", "L", "L"],
    ["J", "A", "O", "P", "B", "B", "B", "B", "B", "B", "B", "B", "B", "P", "O", "L", "L"],
    ["J", "A", "O", "O", "B", "B", "B", "B", "B", "B", "B", "B", "B", "O", "O", "L", "L"],
    ["J", "A", "O", "B", "B", "P", "O", "B", "B", "B", "O", "P", "B", "B", "O", "L", "C"],
    ["J", "O", "O", "P", "P", "O", "Q", "P", "P", "P", "Q", "O", "P", "P", "O", "O", "L"],
    ["J", "O", "P", "P", "P", "P", "P", "P", "O", "P", "P", "P", "P", "P", "P", "O", "L"],
    ["J", "O", "P", "P", "P", "E", "P", "P", "P", "P", "P", "E", "P", "P", "P", "O", "C"],
    ["J", "O", "P", "P", "P", "P", "E", "P", "F", "F", "E", "P", "P", "P", "P", "O", "C"],
    ["J", "N", "O", "P", "P", "P", "P", "E", "E", "E", "P", "P", "P", "P", "O", "M", "C"],
    ["J", "N", "N", "O", "P", "P", "P", "P", "P", "P", "P", "P", "P", "O", "M", "M", "C"],
    ["J", "N", "Q", "Q", "H", "O", "O", "P", "P", "P", "O", "O", "O", "Q", "Q", "Q", "L"],
    ["J", "Q", "Q", "Q", "H", "H", "O", "O", "O", "O", "O", "Q", "K", "Q", "Q", "Q", "C"],
    ["D", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "C", "C", "C", "C", "C", "C", "C", "C"],
  ],
 regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: white,
    Q: lavenderRose,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
