import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/609",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C", "C", "C"],
    ["A", "D", "A", "A", "A", "D", "B", "B", "B", "B", "C", "C", "C", "C"],
    ["A", "D", "D", "D", "D", "D", "B", "B", "B", "B", "C", "E", "C", "C"],
    ["A", "D", "D", "D", "D", "B", "B", "B", "B", "C", "C", "E", "C", "C"],
    ["A", "A", "D", "F", "D", "D", "B", "B", "B", "B", "B", "B", "C", "C"],
    ["A", "A", "D", "F", "F", "B", "B", "B", "B", "B", "B", "C", "C", "C"],
    ["G", "A", "F", "F", "F", "F", "B", "B", "H", "B", "B", "B", "C", "C"],
    ["G", "G", "G", "F", "F", "B", "B", "H", "H", "B", "I", "C", "C", "C"],
    ["G", "G", "G", "J", "J", "B", "H", "H", "H", "H", "I", "I", "I", "K"],
    ["G", "G", "G", "G", "J", "J", "L", "L", "L", "I", "I", "I", "K", "K"],
    ["G", "G", "G", "J", "J", "J", "J", "L", "M", "I", "I", "K", "K", "N"],
    ["G", "G", "G", "J", "J", "J", "J", "J", "M", "J", "J", "K", "K", "N"],
    ["G", "G", "J", "J", "J", "J", "J", "J", "J", "J", "J", "J", "K", "K"],
    ["G", "G", "J", "J", "J", "J", "J", "J", "J", "J", "J", "J", "J", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
