import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lavenderRose,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/641",
  size: 18,
  colorRegions: [
    ["A", "A", "A", "E", "E", "E", "E", "E", "E", "E", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "K", "K", "K", "K", "O", "O", "O", "O", "L", "L", "L", "L", "L", "J", "J", "J", "B"],
    ["A", "K", "L", "R", "O", "O", "H", "H", "O", "O", "O", "P", "P", "L", "L", "L", "J", "E"],
    ["A", "K", "L", "R", "O", "H", "H", "H", "H", "H", "O", "O", "P", "P", "P", "L", "J", "E"],
    ["E", "K", "L", "R", "O", "O", "O", "O", "H", "H", "H", "O", "O", "P", "P", "L", "J", "E"],
    ["E", "K", "L", "O", "G", "G", "G", "O", "O", "O", "H", "H", "O", "O", "P", "L", "Q", "E"],
    ["E", "K", "L", "O", "O", "O", "G", "G", "G", "O", "O", "H", "H", "O", "O", "Q", "Q", "E"],
    ["E", "Q", "Q", "O", "F", "F", "O", "G", "G", "G", "O", "O", "H", "H", "O", "O", "Q", "E"],
    ["E", "Q", "Q", "O", "F", "F", "O", "G", "G", "G", "G", "O", "O", "H", "H", "O", "Q", "E"],
    ["E", "Q", "O", "G", "O", "O", "G", "G", "G", "O", "O", "G", "O", "H", "H", "O", "O", "E"],
    ["E", "Q", "O", "G", "G", "G", "G", "G", "O", "F", "F", "O", "O", "O", "H", "H", "O", "E"],
    ["E", "E", "O", "G", "G", "G", "G", "G", "O", "F", "F", "O", "G", "O", "H", "H", "O", "D"],
    ["E", "E", "O", "G", "G", "G", "G", "G", "G", "O", "O", "G", "G", "O", "H", "O", "O", "D"],
    ["E", "O", "G", "G", "O", "O", "G", "G", "G", "G", "G", "G", "G", "O", "O", "O", "I", "D"],
    ["E", "O", "G", "O", "F", "F", "O", "G", "O", "O", "O", "O", "O", "N", "N", "N", "I", "D"],
    ["C", "O", "G", "O", "F", "O", "O", "O", "M", "M", "M", "M", "M", "M", "M", "N", "I", "D"],
    ["C", "O", "O", "O", "O", "E", "E", "I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "D"],
    ["C", "C", "C", "C", "C", "C", "E", "E", "E", "E", "E", "E", "E", "E", "E", "D", "D", "D"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: lavenderRose,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;