import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lavenderRose,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/712",
  size: 15,
  colorRegions: [
    ["E", "E", "E", "E", "E", "E", "E", "E", "F", "F", "C", "C", "B", "B", "B"],
    ["E", "E", "E", "E", "C", "C", "C", "C", "C", "F", "C", "C", "C", "C", "B"],
    ["E", "E", "C", "C", "C", "A", "A", "A", "A", "C", "C", "C", "C", "C", "B"],
    ["K", "C", "C", "C", "C", "A", "A", "A", "C", "C", "K", "C", "K", "K", "B"],
    ["K", "K", "K", "K", "K", "A", "K", "A", "A", "K", "K", "K", "K", "K", "K"],
    ["A", "A", "K", "K", "G", "A", "K", "K", "K", "K", "K", "A", "K", "A", "I"],
    ["A", "A", "K", "G", "G", "A", "A", "A", "K", "K", "K", "A", "A", "A", "I"],
    ["A", "G", "K", "K", "G", "A", "A", "A", "A", "A", "K", "K", "A", "A", "I"],
    ["A", "O", "G", "G", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "I"],
    ["A", "G", "G", "A", "A", "A", "A", "A", "G", "G", "H", "H", "H", "N", "I"],
    ["A", "O", "G", "A", "A", "A", "A", "G", "J", "J", "H", "N", "N", "N", "I"],
    ["A", "A", "A", "A", "A", "A", "G", "G", "G", "J", "H", "N", "O", "O", "I"],
    ["L", "A", "A", "A", "G", "G", "G", "D", "D", "J", "N", "N", "O", "I", "I"],
    ["L", "L", "L", "M", "M", "G", "O", "D", "D", "N", "N", "O", "O", "I", "I"],
    ["L", "M", "M", "M", "M", "O", "O", "O", "D", "D", "D", "O", "I", "I", "I"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: lavenderRose,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: macNCheese,
    M: lightGreen,
    N: atomicTangerine,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
