import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/624",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "B", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "B", "B", "D", "D", "D", "D", "C", "C", "C", "C", "C"],
    ["A", "E", "B", "B", "B", "D", "D", "C", "C", "C", "F", "C", "C", "C"],
    ["A", "E", "B", "B", "B", "D", "D", "D", "F", "F", "F", "F", "C", "C"],
    ["A", "A", "A", "B", "B", "D", "G", "G", "F", "F", "F", "F", "F", "H"],
    ["A", "A", "A", "A", "B", "B", "G", "I", "F", "F", "H", "H", "H", "H"],
    ["A", "A", "A", "A", "B", "B", "B", "I", "I", "I", "I", "I", "H", "H"],
    ["A", "A", "A", "A", "B", "B", "J", "J", "I", "I", "I", "I", "H", "K"],
    ["A", "A", "B", "B", "B", "B", "J", "J", "J", "L", "L", "L", "H", "K"],
    ["A", "A", "M", "B", "B", "B", "J", "J", "J", "N", "N", "N", "H", "K"],
    ["A", "A", "M", "M", "B", "B", "J", "J", "J", "J", "N", "N", "H", "H"],
    ["A", "A", "A", "M", "M", "M", "M", "M", "J", "J", "J", "J", "J", "J"],
    ["A", "A", "M", "M", "M", "M", "M", "M", "M", "M", "J", "J", "J", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
