import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lavenderRose,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/711",
  size: 18,
  colorRegions: [
    ["G", "E", "A", "A", "A", "P", "P", "P", "P", "P", "P", "P", "P", "O", "O", "O", "O", "I"],
    ["E", "A", "A", "A", "J", "J", "J", "P", "P", "P", "P", "P", "O", "O", "O", "O", "O", "I"],
    ["J", "A", "A", "A", "A", "J", "J", "P", "P", "J", "O", "O", "O", "J", "J", "C", "C", "P"],
    ["J", "J", "J", "A", "A", "A", "J", "P", "J", "J", "O", "O", "J", "J", "J", "A", "G", "C"],
    ["J", "K", "K", "A", "A", "A", "A", "A", "G", "G", "G", "O", "J", "J", "J", "A", "A", "C"],
    ["J", "K", "J", "A", "A", "A", "A", "A", "A", "A", "G", "G", "J", "A", "A", "J", "J", "J"],
    ["N", "N", "N", "A", "A", "F", "A", "A", "A", "A", "A", "G", "A", "A", "N", "N", "N", "N"],
    ["N", "N", "N", "N", "A", "A", "G", "A", "A", "A", "A", "A", "A", "N", "N", "N", "N", "N"],
    ["L", "L", "L", "A", "A", "A", "G", "G", "A", "A", "A", "A", "G", "G", "G", "N", "N", "N"],
    ["N", "N", "L", "A", "L", "A", "N", "N", "L", "A", "A", "A", "A", "A", "A", "N", "N", "N"],
    ["N", "F", "L", "A", "L", "A", "D", "D", "L", "A", "A", "A", "A", "L", "A", "A", "L", "L"],
    ["N", "F", "L", "A", "L", "A", "D", "D", "D", "L", "L", "L", "A", "L", "L", "A", "A", "L"],
    ["D", "D", "D", "A", "D", "A", "M", "D", "D", "D", "D", "D", "A", "D", "D", "D", "A", "D"],
    ["K", "M", "A", "M", "A", "M", "M", "M", "M", "M", "M", "M", "A", "B", "B", "M", "A", "M"],
    ["B", "K", "B", "B", "B", "B", "B", "B", "M", "B", "M", "B", "A", "B", "B", "B", "A", "B"],
    ["R", "R", "R", "R", "R", "R", "R", "R", "R", "B", "B", "A", "A", "R", "R", "A", "A", "R"],
    ["R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "Q", "Q", "Q", "Q"],
    ["Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "Q", "H", "H"],
  ],
  regionColors: {
  A: halfBaked,
  B: nomad,
  C: anakiwa,
  D: atomicTangerine,
  E: saharaSand,
  F: bittersweet,
  G: celadon,
  H: chardonnay,
  I: lightOrchid,
  J: coldPurple,
  K: turquoiseBlue,
  L: lavenderRose,
  M: turquoiseBlue,
  N: emerald,
  O: white,
  P: lightWisteria,
  Q: macNCheese,
  R: altoMain,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
