import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/702",
  size: 15,
  colorRegions: [
    ["E", "E", "J", "J", "D", "J", "J", "J", "J", "I", "I", "J", "J", "J", "J"],
    ["E", "J", "J", "B", "G", "C", "A", "E", "J", "J", "I", "J", "E", "E", "E"],
    ["E", "I", "I", "I", "G", "G", "I", "F", "F", "J", "I", "I", "G", "A", "A"],
    ["N", "N", "N", "N", "I", "N", "A", "F", "C", "D", "N", "N", "N", "N", "N"],
    ["E", "N", "N", "N", "N", "N", "N", "N", "B", "F", "N", "N", "N", "N", "N"],
    ["N", "H", "N", "N", "N", "H", "N", "N", "N", "J", "N", "I", "N", "N", "N"],
    ["N", "N", "H", "N", "H", "N", "N", "G", "N", "J", "I", "I", "F", "F", "N"],
    ["N", "N", "N", "N", "N", "I", "N", "N", "N", "J", "N", "G", "F", "D", "B"],
    ["N", "N", "H", "N", "H", "N", "N", "N", "N", "J", "N", "N", "A", "C", "F"],
    ["N", "H", "N", "H", "N", "H", "N", "H", "H", "J", "O", "N", "N", "N", "A"],
    ["I", "M", "M", "M", "I", "A", "A", "A", "A", "M", "O", "O", "O", "O", "O"],
    ["M", "A", "K", "M", "I", "I", "I", "A", "A", "L", "O", "O", "O", "O", "O"],
    ["M", "K", "K", "I", "I", "I", "I", "I", "M", "L", "L", "M", "I", "I", "I"],
    ["I", "M", "L", "I", "I", "I", "I", "I", "M", "K", "M", "I", "I", "A", "A"],
    ["J", "J", "I", "I", "J", "J", "J", "I", "I", "J", "J", "J", "I", "I", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "Ja-Nice",
  creatorLink: "https://www.linkedin.com/in/jan-hollmann-215a85315",
};

export default level;
