import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/535",
  size: 16,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B"],
    ["A", "A", "A", "C", "C", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B"],
    ["A", "A", "A", "A", "C", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B"],
    ["D", "E", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "E", "E", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "D", "E", "A", "A", "A", "A", "F", "G", "G", "G", "G", "A", "A", "A", "A"],
    ["D", "D", "A", "A", "A", "A", "F", "F", "G", "G", "G", "G", "A", "A", "A", "A"],
    ["D", "D", "D", "A", "A", "F", "F", "F", "G", "G", "G", "G", "H", "I", "I", "I"],
    ["D", "D", "D", "D", "A", "J", "J", "J", "G", "G", "H", "H", "H", "H", "I", "I"],
    ["D", "D", "D", "D", "D", "D", "D", "D", "D", "H", "H", "K", "H", "H", "H", "I"],
    ["D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "K", "K", "K", "H", "H", "H"],
    ["D", "D", "D", "D", "D", "D", "D", "D", "L", "D", "D", "M", "M", "M", "H", "H"],
    ["D", "D", "D", "D", "D", "D", "D", "L", "L", "L", "D", "D", "D", "D", "H", "H"],
    ["D", "D", "D", "D", "N", "N", "N", "N", "L", "L", "D", "D", "D", "O", "H", "H"],
    ["D", "D", "D", "D", "N", "N", "N", "P", "L", "D", "D", "D", "D", "O", "O", "O"],
    ["D", "D", "D", "D", "P", "P", "P", "P", "P", "D", "D", "D", "O", "O", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
