import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/513",
  size: 15,
  colorRegions: [
    ["C", "C", "C", "C", "C", "C", "G", "G", "G", "G", "G", "G", "G", "G", "G"],
    ["C", "C", "A", "A", "G", "G", "G", "G", "G", "G", "D", "M", "G", "G", "G"],
    ["C", "C", "A", "G", "G", "G", "G", "G", "G", "F", "L", "D", "M", "G", "G"],
    ["B", "B", "G", "G", "G", "G", "G", "G", "F", "F", "L", "L", "D", "M", "G"],
    ["B", "B", "G", "G", "G", "G", "G", "F", "F", "O", "F", "L", "D", "M", "G"],
    ["B", "I", "G", "G", "G", "G", "F", "F", "F", "F", "F", "L", "D", "M", "G"],
    ["I", "I", "G", "G", "G", "F", "F", "F", "E", "F", "F", "L", "D", "M", "G"],
    ["G", "I", "G", "G", "F", "F", "F", "F", "F", "F", "F", "L", "D", "M", "G"],
    ["G", "G", "G", "F", "F", "F", "K", "F", "F", "F", "L", "L", "D", "M", "G"],
    ["G", "G", "F", "F", "N", "F", "F", "F", "F", "F", "L", "D", "M", "G", "G"],
    ["G", "D", "L", "L", "F", "F", "F", "L", "L", "L", "D", "M", "M", "G", "J"],
    ["G", "M", "D", "D", "L", "L", "L", "L", "L", "D", "M", "M", "J", "J", "J"],
    ["G", "G", "M", "D", "D", "D", "D", "D", "D", "M", "M", "J", "J", "J", "H"],
    ["H", "H", "H", "M", "M", "M", "M", "M", "M", "H", "H", "H", "H", "H", "H"],
    ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "Meyina",
  creatorLink: "https://www.instagram.com/meyina009/",
};

export default level;
