import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/625",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["C", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B"],
    ["C", "A", "A", "A", "D", "A", "D", "A", "B", "E", "E", "B", "B", "B"],
    ["C", "C", "C", "C", "D", "D", "D", "D", "D", "E", "E", "B", "F", "G"],
    ["C", "C", "C", "D", "D", "D", "D", "D", "E", "E", "F", "F", "F", "G"],
    ["C", "C", "C", "D", "D", "D", "D", "H", "H", "F", "F", "I", "I", "G"],
    ["C", "C", "C", "C", "C", "D", "H", "H", "F", "F", "F", "I", "I", "I"],
    ["C", "C", "C", "C", "D", "D", "D", "H", "H", "F", "F", "F", "I", "I"],
    ["C", "C", "C", "C", "C", "D", "J", "H", "H", "H", "K", "L", "I", "L"],
    ["C", "C", "C", "C", "J", "J", "J", "H", "H", "H", "K", "L", "L", "L"],
    ["C", "C", "C", "J", "J", "J", "J", "J", "H", "H", "K", "L", "L", "L"],
    ["M", "C", "C", "C", "J", "N", "N", "N", "H", "H", "K", "L", "L", "L"],
    ["M", "M", "C", "C", "J", "J", "N", "N", "N", "H", "H", "H", "H", "L"],
    ["M", "M", "M", "M", "M", "M", "N", "N", "N", "N", "H", "H", "H", "L"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
