import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lavenderRose,
  lightGreen,
  lightOrchid,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/502",
  size: 15,
  colorRegions: [
    ["D", "D", "D", "J", "J", "J", "J", "J", "J", "J", "J", "J", "J", "A", "L"],
    ["J", "J", "J", "J", "J", "J", "J", "J", "M", "J", "J", "J", "A", "A", "L"],
    ["J", "J", "J", "J", "J", "J", "C", "C", "C", "M", "C", "C", "M", "L", "L"],
    ["C", "C", "C", "C", "C", "C", "C", "B", "B", "C", "M", "M", "C", "C", "B"],
    ["G", "C", "C", "C", "C", "C", "B", "B", "B", "B", "C", "M", "C", "B", "B"],
    ["C", "C", "C", "C", "F", "F", "F", "F", "B", "B", "C", "M", "B", "B", "L"],
    ["C", "K", "K", "F", "F", "F", "F", "F", "F", "F", "O", "B", "B", "B", "L"],
    ["K", "K", "F", "F", "E", "I", "I", "I", "F", "F", "F", "B", "B", "O", "L"],
    ["K", "F", "F", "F", "F", "I", "B", "I", "I", "I", "F", "B", "B", "O", "O"],
    ["K", "K", "I", "I", "I", "B", "B", "B", "B", "B", "O", "B", "B", "B", "O"],
    ["K", "K", "O", "O", "I", "I", "B", "B", "B", "O", "O", "O", "B", "B", "O"],
    ["K", "O", "O", "O", "O", "I", "I", "O", "I", "O", "O", "O", "O", "B", "B"],
    ["O", "O", "O", "O", "O", "O", "I", "O", "O", "O", "O", "O", "O", "O", "B"],
    ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "O", "O", "O", "N", "N"],
    ["H", "H", "H", "H", "H", "O", "O", "O", "O", "O", "O", "O", "H", "H", "N"],
  ],
  regionColors: {
    A: lavenderRose,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "Emi S/Meyina",
  creatorLink: "https://www.instagram.com/meyina009/",
};

export default level;
