import {

  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/537",
  size: 17,
  colorRegions: [
    ["D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "A", "A", "A", "A", "A", "A"],
    ["D", "D", "D", "D", "D", "I", "I", "I", "I", "I", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "D", "D", "D", "D", "I", "I", "I", "I", "I", "I", "I", "I", "A", "A", "A", "A"],
    ["D", "D", "D", "D", "Q", "Q", "Q", "J", "J", "E", "J", "P", "P", "P", "P", "P", "P"],
    ["D", "D", "D", "Q", "J", "Q", "J", "J", "J", "E", "J", "J", "J", "P", "P", "P", "P"],
    ["D", "D", "D", "D", "J", "Q", "Q", "J", "J", "J", "E", "J", "J", "J", "P", "P", "P"],
    ["D", "D", "D", "Q", "Q", "J", "J", "J", "J", "E", "E", "E", "E", "N", "N", "N", "N"],
    ["D", "D", "D", "D", "D", "J", "J", "J", "J", "J", "J", "J", "N", "N", "N", "M", "N"],
    ["D", "D", "D", "D", "F", "F", "C", "F", "F", "C", "F", "F", "K", "K", "K", "K", "K"],
    ["D", "D", "D", "F", "F", "F", "C", "F", "F", "C", "F", "F", "F", "K", "K", "K", "K"],
    ["D", "D", "F", "F", "F", "F", "C", "C", "C", "C", "F", "F", "F", "F", "K", "K", "K"],
    ["D", "D", "J", "J", "F", "C", "G", "C", "C", "G", "C", "F", "J", "J", "K", "K", "K"],
    ["D", "D", "J", "J", "J", "C", "C", "C", "C", "C", "C", "J", "J", "J", "K", "K", "K"],
    ["D", "D", "J", "J", "C", "C", "C", "C", "C", "C", "C", "C", "J", "J", "L", "L", "L"],
    ["L", "L", "L", "L", "C", "C", "C", "L", "L", "C", "C", "C", "L", "L", "L", "L", "B"],
    ["B", "B", "B", "B", "O", "O", "B", "B", "B", "B", "O", "O", "B", "B", "B", "B", "B"],
    ["B", "H", "H", "O", "O", "O", "H", "H", "H", "H", "O", "O", "O", "H", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: white,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
  },
  solutionsCount: 1,
  createdBy: "Meyina",
  creatorLink: "https://www.instagram.com/meyina009/",
};

export default level;