import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/687",
  size: 17,
  colorRegions: [
    ["E", "B", "B", "E", "E", "E", "L", "O", "O", "O", "L", "E", "E", "G", "E", "E", "E"],
    ["B", "B", "B", "B", "E", "O", "O", "J", "A", "J", "O", "E", "P", "E", "E", "E", "E"],
    ["B", "B", "B", "B", "O", "I", "A", "A", "F", "A", "A", "O", "E", "E", "E", "E", "E"],
    ["E", "B", "B", "L", "O", "A", "D", "C", "C", "C", "D", "O", "O", "L", "E", "E", "G"],
    ["E", "G", "E", "O", "O", "A", "C", "C", "C", "C", "C", "A", "J", "O", "E", "E", "E"],
    ["E", "E", "O", "O", "A", "D", "F", "C", "Q", "C", "F", "D", "A", "O", "O", "E", "E"],
    ["E", "E", "G", "O", "J", "A", "C", "C", "C", "C", "C", "A", "J", "O", "E", "G", "E"],
    ["E", "E", "E", "L", "O", "A", "I", "C", "C", "C", "C", "I", "O", "L", "E", "E", "E"],
    ["G", "E", "E", "E", "O", "P", "A", "A", "Q", "A", "D", "A", "O", "E", "E", "E", "E"],
    ["E", "E", "E", "E", "E", "O", "O", "J", "A", "J", "O", "O", "P", "E", "E", "E", "E"],
    ["H", "E", "E", "E", "E", "E", "L", "O", "Q", "O", "L", "E", "E", "E", "E", "E", "E"],
    ["H", "H", "H", "H", "H", "E", "H", "E", "F", "E", "E", "E", "H", "E", "H", "H", "E"],
    ["H", "H", "N", "N", "N", "N", "N", "H", "Q", "H", "H", "H", "H", "H", "N", "N", "N"],
    ["N", "N", "M", "M", "N", "N", "M", "N", "N", "N", "N", "N", "N", "H", "N", "M", "M"],
    ["N", "M", "M", "M", "M", "M", "M", "M", "Q", "M", "M", "N", "N", "N", "M", "M", "M"],
    ["M", "M", "M", "K", "M", "M", "M", "M", "M", "M", "M", "M", "K", "M", "M", "M", "M"],
    ["K", "M", "M", "K", "K", "K", "M", "M", "Q", "M", "K", "M", "K", "K", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: white,
  },
  solutionsCount: 1,
  createdBy: "Ja-Nice",
  creatorLink: "https://www.linkedin.com/in/jan-hollmann-215a85315",
};

export default level;