import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/605",
  size: 16,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "D", "D", "D", "D", "B", "E", "E", "E", "B", "E", "B", "B", "B"],
    ["A", "A", "F", "D", "D", "D", "D", "B", "B", "E", "E", "E", "E", "B", "B", "B"],
    ["A", "A", "F", "F", "G", "G", "G", "B", "B", "E", "E", "E", "E", "E", "E", "B"],
    ["A", "A", "A", "A", "G", "G", "G", "B", "B", "E", "H", "E", "E", "E", "E", "B"],
    ["A", "A", "A", "A", "A", "G", "G", "B", "B", "E", "H", "H", "H", "H", "H", "B"],
    ["I", "A", "A", "A", "A", "G", "G", "G", "G", "G", "G", "J", "J", "J", "J", "B"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "G", "J", "J", "J", "J", "B"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "K", "K", "G", "G", "L", "J", "J", "J"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "G", "L", "L", "L", "M", "J"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "G", "G", "L", "L", "M", "J"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "N", "O", "O"],
    ["I", "I", "I", "I", "I", "I", "P", "I", "I", "I", "I", "I", "N", "N", "O", "O"],
    ["I", "I", "I", "I", "I", "P", "P", "I", "I", "I", "I", "I", "I", "N", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
