import {
  anakiwa,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  white,
} from "../colors";

const level = {
  path: "/community-level/727",
  size: 15,
  colorRegions: [
    ["D", "D", "L", "L", "L", "F", "F", "F", "L", "L", "E", "E", "E", "E", "E"],
    ["K", "K", "D", "L", "F", "F", "H", "H", "F", "L", "E", "E", "E", "E", "E"],
    ["K", "K", "D", "L", "I", "I", "O", "H", "F", "L", "L", "E", "E", "E", "E"],
    ["K", "L", "L", "L", "I", "I", "H", "H", "F", "L", "L", "E", "E", "E", "E"],
    ["K", "L", "L", "L", "I", "O", "H", "F", "F", "F", "L", "E", "E", "E", "E"],
    ["M", "L", "L", "L", "L", "H", "F", "F", "F", "F", "L", "E", "E", "E", "E"],
    ["M", "L", "L", "L", "L", "F", "F", "F", "G", "G", "F", "L", "E", "E", "E"],
    ["M", "L", "K", "L", "L", "F", "F", "G", "G", "G", "G", "L", "L", "E", "E"],
    ["M", "K", "L", "L", "L", "F", "F", "C", "G", "G", "G", "G", "L", "E", "E"],
    ["M", "L", "L", "L", "L", "L", "F", "F", "C", "N", "N", "N", "L", "L", "E"],
    ["M", "L", "K", "L", "L", "L", "F", "F", "C", "A", "A", "N", "N", "L", "E"],
    ["M", "K", "L", "L", "L", "L", "L", "F", "F", "C", "C", "A", "A", "L", "E"],
    ["M", "L", "L", "L", "L", "L", "B", "B", "B", "L", "C", "C", "C", "L", "E"],
    ["M", "L", "K", "J", "J", "J", "J", "J", "J", "L", "L", "C", "F", "L", "E"],
    ["M", "K", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "F", "E", "E"],
  ],
  regionColors: {
    A: lightWisteria,
    B: lightOrchid,
    C: anakiwa,
    D: celadon,
    E: coldPurple,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: chardonnay,
    J: lightGreen,
    K: emerald,
    L: white,
    M: macNCheese,
    N: halfBaked,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
