import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/644",
  size: 18,
  colorRegions: [
    ["C", "C", "H", "H", "H", "H", "H", "C", "C", "C", "C", "C", "C", "L", "L", "L", "C", "C"],
    ["C", "H", "H", "H", "H", "H", "H", "H", "C", "C", "C", "C", "K", "K", "L", "K", "K", "K"],
    ["H", "H", "H", "H", "H", "H", "H", "H", "H", "C", "K", "R", "R", "R", "R", "R", "R", "R"],
    ["H", "H", "G", "G", "G", "G", "G", "H", "H", "C", "K", "R", "R", "R", "D", "R", "R", "R"],
    ["C", "H", "G", "M", "G", "M", "G", "H", "C", "C", "K", "R", "R", "D", "D", "D", "R", "R"],
    ["C", "C", "G", "G", "G", "G", "G", "C", "C", "C", "C", "R", "R", "R", "D", "R", "R", "R"],
    ["C", "C", "G", "F", "G", "F", "G", "J", "J", "C", "C", "R", "R", "D", "D", "D", "R", "R"],
    ["C", "C", "C", "G", "F", "G", "J", "J", "J", "J", "C", "R", "D", "D", "D", "D", "D", "R"],
    ["C", "C", "C", "G", "G", "G", "J", "J", "J", "C", "C", "R", "R", "R", "Q", "R", "R", "R"],
    ["C", "J", "J", "J", "J", "J", "J", "J", "J", "C", "J", "R", "R", "R", "Q", "R", "R", "R"],
    ["C", "J", "E", "E", "E", "E", "E", "E", "E", "C", "J", "R", "R", "R", "R", "R", "R", "R"],
    ["C", "E", "E", "A", "A", "E", "B", "B", "E", "E", "C", "C", "C", "L", "L", "L", "N", "N"],
    ["C", "E", "E", "E", "A", "E", "B", "E", "E", "C", "C", "C", "C", "L", "C", "L", "N", "N"],
    ["C", "E", "E", "E", "E", "E", "B", "E", "C", "C", "C", "C", "L", "C", "C", "C", "L", "N"],
    ["C", "E", "E", "I", "I", "E", "E", "E", "C", "C", "C", "C", "C", "C", "C", "C", "N", "C"],
    ["C", "E", "I", "I", "E", "E", "E", "P", "P", "P", "P", "P", "P", "C", "C", "C", "C", "C"],
    ["C", "E", "E", "E", "E", "E", "P", "P", "O", "O", "C", "C", "C", "C", "C", "O", "C", "C"],
    ["P", "P", "P", "P", "P", "P", "P", "P", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;