import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/637",
  size: 18,
  colorRegions: [
    ["C", "C", "B", "B", "B", "B", "B", "C", "C", "C", "J", "J", "P", "P", "P", "P", "A", "A"],
    ["C", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "J", "J", "J", "P", "P", "A", "A"],
    ["B", "H", "B", "B", "B", "B", "B", "H", "B", "C", "C", "J", "J", "J", "O", "P", "A", "A"],
    ["B", "B", "H", "B", "B", "B", "H", "B", "B", "C", "C", "J", "J", "O", "O", "O", "O", "A"],
    ["B", "B", "H", "B", "B", "B", "Q", "B", "B", "C", "C", "L", "O", "O", "O", "D", "O", "O"],
    ["B", "B", "H", "B", "B", "B", "H", "B", "B", "C", "L", "L", "L", "L", "D", "D", "D", "O"],
    ["B", "H", "B", "B", "B", "B", "B", "H", "B", "C", "L", "L", "L", "L", "L", "D", "D", "K"],
    ["C", "B", "B", "B", "B", "B", "B", "B", "C", "C", "L", "L", "L", "L", "L", "D", "D", "K"],
    ["C", "C", "B", "B", "B", "B", "B", "C", "C", "L", "L", "L", "L", "L", "D", "D", "D", "K"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "L", "L", "D", "D", "D", "D", "D", "D", "D", "K"],
    ["C", "C", "C", "C", "C", "C", "C", "C", "D", "D", "D", "D", "D", "D", "D", "D", "K", "K"],
    ["N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D", "F", "F", "F", "F", "F", "F", "F"],
    ["N", "I", "I", "N", "N", "N", "G", "G", "G", "N", "D", "R", "M", "R", "M", "R", "M", "R"],
    ["N", "N", "I", "N", "N", "N", "N", "N", "G", "N", "D", "R", "R", "R", "R", "R", "R", "R"],
    ["N", "N", "I", "N", "E", "N", "G", "G", "G", "N", "D", "R", "M", "R", "M", "R", "M", "R"],
    ["N", "N", "I", "N", "N", "N", "G", "N", "N", "N", "D", "R", "R", "R", "R", "R", "R", "R"],
    ["N", "I", "I", "I", "N", "N", "G", "G", "G", "N", "D", "R", "D", "R", "D", "R", "D", "R"],
    ["D", "N", "N", "N", "N", "N", "N", "N", "N", "N", "D", "D", "D", "D", "D", "D", "D", "D"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Jess",
  creatorLink: "",
};

export default level;