import {
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lavenderRose,
  lightOrchid,
  lightWisteria,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/728",
  size: 14,
  colorRegions: [
    ["F", "C", "F", "F", "A", "G", "G", "G", "G", "A", "I", "H", "A", "G"],
    ["B", "C", "B", "B", "A", "C", "C", "C", "C", "D", "D", "D", "D", "A"],
    ["F", "C", "E", "F", "A", "K", "J", "J", "K", "D", "I", "D", "D", "G"],
    ["F", "C", "F", "G", "A", "G", "G", "G", "G", "D", "H", "F", "D", "F"],
    ["D", "D", "D", "D", "C", "C", "C", "C", "C", "C", "D", "D", "D", "A"],
    ["G", "B", "N", "G", "B", "E", "K", "J", "C", "C", "H", "N", "C", "H"],
    ["G", "B", "M", "G", "B", "M", "M", "J", "N", "C", "H", "M", "C", "H"],
    ["G", "B", "N", "G", "B", "N", "J", "M", "M", "C", "H", "M", "C", "H"],
    ["G", "B", "M", "G", "B", "B", "J", "K", "L", "C", "H", "N", "C", "H"],
    ["D", "A", "A", "A", "B", "B", "B", "B", "B", "C", "A", "A", "A", "A"],
    ["I", "A", "I", "G", "A", "H", "H", "H", "H", "D", "H", "I", "B", "I"],
    ["H", "A", "A", "F", "A", "K", "J", "K", "J", "D", "I", "L", "B", "I"],
    ["D", "A", "A", "A", "A", "B", "B", "B", "B", "D", "C", "C", "C", "C"],
    ["H", "D", "G", "F", "D", "H", "H", "H", "H", "D", "I", "I", "B", "I"],
  ],
  regionColors: {
    A: saharaSand,
    B: celadon,
    C: halfBaked,
    D: anakiwa,
    E: chardonnay,
    F: periwinkle,
    G: emerald,
    H: coldPurple,
    I: turquoiseBlue,
    J: bittersweet,
    K: lavenderRose,
    L: lightOrchid,
    M: atomicTangerine,
    N: lightWisteria,
  },
  solutionsCount: 1,
  createdBy: "Ja-Nice",
  creatorLink: "https://www.linkedin.com/in/jan-hollmann-215a85315",
};

export default level;
